name: Update Game Data

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 2 * 1,2,3,11,12 *"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions: write-all

jobs:
  cbb:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Fetch CBB data
        run: |
          pip install -r requirements.txt
          python -m scraper cbb fetch --debug --num-threads 1 > games.csv

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: brockwsmith225
          author_email: brockwsmith@gatech.edu
          message: 'Updated CBB data'

